export const data = [
  {
    nom: 'BBIBP-CorV',
    inventeurs: ['Sinopharm'],
    lieux: ['Chine'],
    technologie: 'virus inactivé',
    quantite: 420,
    prix: 17,
    approuve: true,
    img: 'bbibp-corv.jpg',
    reservation: false,
  }, {
    nom: 'Sputnik V',
    inventeurs: ['Gamaleya'],
    lieux: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prix: 12,
    approuve: false,
    img: 'sputnik-v.jpg',
    reservation: false,
  }, {
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    lieux: ['Royaume Unis', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantite: 5028,
    prix: 1.78,
    approuve: false,
    img: 'azd1222.jpg',
    reservation: false,
  }, {
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieux: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantite: 980,
    prix: 14,
    approuve: true,
    img: 'tozinameran.jpg',
    reservation: false,
  }, {
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieux: ['USA'],
    technologie: 'ARN messager',
    quantite: 240,
    prix: 28,
    approuve: false,
    img: 'mrna-1273.jpg',
    reservation: false,
  }, {
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieux: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantite: 110,
    prix: 31,
    approuve: false,
    img: 'ad26-cov2-s.jpg',
    reservation: false,
  }];
